/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    ComplexDialog: typeof import('./src/components/examples/ComplexDialog.vue')['default']
    ConfirmDialog: typeof import('./src/components/examples/ConfirmDialog.vue')['default']
    CustomDataTable: typeof import('./src/components/CustomDataTable.vue')['default']
    CustomizableDialog: typeof import('./src/components/examples/CustomizableDialog.vue')['default']
    DialogContainer: typeof import('./src/components/DialogContainer.vue')['default']
    FontSizeControl: typeof import('./src/components/FontSizeControl.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Level1Dialog: typeof import('./src/components/examples/Level1Dialog.vue')['default']
    Level2Dialog: typeof import('./src/components/examples/Level2Dialog.vue')['default']
    Level3Dialog: typeof import('./src/components/examples/Level3Dialog.vue')['default']
    ReusableCard: typeof import('./src/components/ReusableCard.vue')['default']
    ReverseLayout: typeof import('./src/components/ReverseLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleDialog: typeof import('./src/components/examples/SimpleDialog.vue')['default']
    TwoRowTabs: typeof import('./src/components/TwoRowTabs.vue')['default']
    UserFormDialog: typeof import('./src/components/examples/UserFormDialog.vue')['default']
  }
}
